name: DTVM_SolSDK Nightly Release

on:
  workflow_dispatch:
    paths:
      - '**'
permissions:
  contents: write

jobs:
  build_and_package: # Renamed job for clarity
    name: Build and Package DTVM_SolSDK Nightly # Updated name
    runs-on: ubuntu-latest
    container:
      image: dtvmdev1/dtvm-sol-dev-x64:1.84.0
    steps:
      - name: Check out code
        uses: actions/checkout@v4 # Use v4
        with:
          lfs: true
          submodules: "true"
      - name: Build the Release
        working-directory: . 
        run: |
          export CUR_PATH=$(pwd)
          # install rust
          /opt/install_rust.sh

          . "$HOME/.cargo/env"
          export PATH=$HOME/.cargo/bin:$PATH

          export LLVM_SYS_160_PREFIX=/opt/llvm16
          export LLVM_DIR=$LLVM_SYS_160_PREFIX/lib/cmake/llvm
          export PATH=$LLVM_SYS_160_PREFIX/bin:$PATH

          ./download_deps.sh
          .ci/package.sh
          # Assuming package.sh creates DTVM_SolSDK-*-nightly.tar.gz in target/release
          ls target/release
      - name: Upload Nightly Artifact # Renamed step
        uses: actions/upload-artifact@v4
        with:
          name: DTVM_SolSDK-nightly-latest # Updated artifact name
          path: target/release/DTVM_SolSDK-*-nightly.tar.gz # Updated path assuming this name
